### ISSUE TITLE
Enable HTTPS callback URI when behind reverse proxy

### ISSUE THREAD

**Issue by dashrandom** [Clem-Fern/rtabby-web-api#21]
Hello, I'm having a bit of an issue as I'm using a reverse proxy to generate and store my SSL certs but when using the oauth login the callback URI is a plain HTTP url, making it fail.

Is there a way I can enable HTTPS for the callback URI without uploading a cert.pem and cert.key file? Thanks!

**Comment by Clem-Fern** [comment]
Hey @dashrandom 

You should be able to enable https on login callback by setting `USE_HTTPS` env variable on `true`.

I just saw that I forgot to document this option when I published the latest release. Sorry about that.

**Comment by dashrandom** [comment]
Thanks for replying @Clem-Fern ! I tried with `USE_HTTPS=true` but it still doesn't seem to be working. I'm getting the same issue about the callback URI being in plain http.

![image](https://github.com/Clem-Fern/rtabby-web-api/assets/9287237/7d7b4d49-60fe-435c-95e2-ee73c56d8a38)

Do I need to expose port 443 from the container instead of 8080 when using the above env variable?

**Comment by Clem-Fern** [comment]
Hey @dashrandom,

0.4.2 version should fix your issue. I replace `USE_HTTPS` by `HTTPS_CALLBACK` and rewrite a bit of code around it.

Release and container image should be available soon (build in progress).

**Comment by dashrandom** [comment]
Much appreciated @Clem-Fern !
