### ISSUE TITLE
Can't connect to server on 'db'

### ISSUE THREAD

**Issue by mihha** [Clem-Fern/rtabby-web-api#7]
Hi,

first of all, thank you for the solution you have provided

I know that it should be straightforward, but after following the steps, this is what I can see in the rtabby_web_api log
```
[2023-12-05T09:30:00Z ERROR rtabby_web_api] Encountered error on database connection: Can't connect to server on 'db' (115)
Error: MysqlConnection(BadConnection("Can't connect to server on 'db' (115)"))
```
The only thing that I have changed in your docker-compose file is the volume for the DB, because I like to have everything in the same folder

I have this under the db
```
volumes:
      - ./database:/var/lib/mysql
```
instead of
```
volumes:
      - database:/var/lib/mysql
```

I also removed the volume definition at the end
```
volumes:
  database:
```

Do you have an idea what could be wrong here?

**Comment by Clem-Fern** [comment]
Hey @mihha,

Sorry to hear that you have trouble with this.

I tried to update my compose file same as you and run into issue. To be sure that i'm experiencing the same problem, could you please send the log of the db container ? 

```
docker logs rtabby-database
```

**Comment by mihha** [comment]
Hi,

sure. Here is the output of the log you have requested

```
2023-12-05 09:20:23+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2023-12-05 09:20:23+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-12-05 09:20:23+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2023-12-05 09:20:23+00:00 [Note] [Entrypoint]: Initializing database files


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mariadb-secure-installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at https://mariadb.com/kb

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.

Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2023-12-05 09:20:29+00:00 [Note] [Entrypoint]: Database files initialized
2023-12-05 09:20:29+00:00 [Note] [Entrypoint]: Starting temporary server
2023-12-05 09:20:29+00:00 [Note] [Entrypoint]: Waiting for server startup
2023-12-05  9:20:29 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 113
2023-12-05  9:20:29 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-12-05  9:20:29 0 [Note] InnoDB: Number of transaction pools: 1
2023-12-05  9:20:29 0 [Note] InnoDB: Using SSE4.2 crc32 instructions
2023-12-05  9:20:29 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2023-12-05  9:20:29 0 [Note] InnoDB: Completed initialization of buffer pool
2023-12-05  9:20:29 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2023-12-05  9:20:29 0 [Note] InnoDB: End of log at LSN=47629
2023-12-05  9:20:29 0 [Note] InnoDB: Opened 3 undo tablespaces
2023-12-05  9:20:29 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2023-12-05  9:20:29 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2023-12-05  9:20:29 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-12-05  9:20:29 0 [Note] InnoDB: log sequence number 47629; transaction id 14
2023-12-05  9:20:29 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-12-05  9:20:29 0 [Note] Plugin 'wsrep-provider' is disabled.
2023-12-05  9:20:29 0 [Warning] 'user' entry 'root@e48c28584f2e' ignored in --skip-name-resolve mode.
2023-12-05  9:20:29 0 [Warning] 'proxies_priv' entry '@% root@e48c28584f2e' ignored in --skip-name-resolve mode.
2023-12-05  9:20:29 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2023-12-05  9:20:29 0 [Note] mariadbd: ready for connections.
Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2023-12-05 09:20:30+00:00 [Note] [Entrypoint]: Temporary server started.
2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: ZZ<-"R@w9;W@zlA/GGHHjF:aGgmLoz<m
2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Creating database tabby
2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Creating user tabby
2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Giving user tabby access to schema tabby
2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)

2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Stopping temporary server
2023-12-05  9:20:33 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2023-12-05  9:20:33 0 [Note] InnoDB: FTS optimize thread exiting.
2023-12-05  9:20:33 0 [Note] InnoDB: Starting shutdown...
2023-12-05  9:20:33 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2023-12-05  9:20:33 0 [Note] InnoDB: Buffer pool(s) dump completed at 231205  9:20:33
2023-12-05  9:20:33 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2023-12-05  9:20:33 0 [Note] InnoDB: Shutdown completed; log sequence number 47629; transaction id 15
2023-12-05  9:20:33 0 [Note] mariadbd: Shutdown complete

2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: Temporary server stopped

2023-12-05 09:20:33+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.

2023-12-05  9:20:33 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 1
2023-12-05  9:20:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-12-05  9:20:33 0 [Note] InnoDB: Number of transaction pools: 1
2023-12-05  9:20:33 0 [Note] InnoDB: Using SSE4.2 crc32 instructions
2023-12-05  9:20:33 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2023-12-05  9:20:33 0 [Note] InnoDB: Completed initialization of buffer pool
2023-12-05  9:20:33 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2023-12-05  9:20:33 0 [Note] InnoDB: End of log at LSN=47629
2023-12-05  9:20:33 0 [Note] InnoDB: Opened 3 undo tablespaces
2023-12-05  9:20:33 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2023-12-05  9:20:33 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2023-12-05  9:20:33 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-12-05  9:20:33 0 [Note] InnoDB: log sequence number 47629; transaction id 14
2023-12-05  9:20:33 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-12-05  9:20:33 0 [Note] Plugin 'wsrep-provider' is disabled.
2023-12-05  9:20:33 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-12-05  9:20:33 0 [Note] InnoDB: Buffer pool(s) load completed at 231205  9:20:33
2023-12-05  9:20:33 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-12-05  9:20:33 0 [Note] Server socket created on IP: '::'.
2023-12-05  9:20:33 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2023-12-05  9:20:33 0 [Note] mariadbd: ready for connections.
Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2023-12-05  9:22:25 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2023-12-05  9:22:25 0 [Note] InnoDB: FTS optimize thread exiting.
2023-12-05  9:22:25 0 [Note] InnoDB: Starting shutdown...
2023-12-05  9:22:25 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2023-12-05  9:22:25 0 [Note] InnoDB: Buffer pool(s) dump completed at 231205  9:22:25
2023-12-05  9:22:25 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2023-12-05  9:22:25 0 [Note] InnoDB: Shutdown completed; log sequence number 47629; transaction id 15
2023-12-05  9:22:25 0 [Note] mariadbd: Shutdown complete

2023-12-05 09:26:01+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2023-12-05 09:26:01+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-12-05 09:26:01+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
2023-12-05 09:26:02+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2023-12-05  9:26:02 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 1
2023-12-05  9:26:02 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-12-05  9:26:02 0 [Note] InnoDB: Number of transaction pools: 1
2023-12-05  9:26:02 0 [Note] InnoDB: Using SSE4.2 crc32 instructions
2023-12-05  9:26:02 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2023-12-05  9:26:02 0 [Note] InnoDB: Completed initialization of buffer pool
2023-12-05  9:26:02 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2023-12-05  9:26:02 0 [Note] InnoDB: End of log at LSN=47629
2023-12-05  9:26:02 0 [Note] InnoDB: Opened 3 undo tablespaces
2023-12-05  9:26:02 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2023-12-05  9:26:02 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2023-12-05  9:26:02 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-12-05  9:26:02 0 [Note] InnoDB: log sequence number 47629; transaction id 14
2023-12-05  9:26:02 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-12-05  9:26:02 0 [Note] Plugin 'wsrep-provider' is disabled.
2023-12-05  9:26:02 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-12-05  9:26:02 0 [Note] InnoDB: Buffer pool(s) load completed at 231205  9:26:02
2023-12-05  9:26:02 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-12-05  9:26:02 0 [Note] Server socket created on IP: '::'.
2023-12-05  9:26:02 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2023-12-05  9:26:02 0 [Note] mariadbd: ready for connections.
Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2023-12-05  9:38:17 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2023-12-05  9:38:17 0 [Note] InnoDB: FTS optimize thread exiting.
2023-12-05  9:38:17 0 [Note] InnoDB: Starting shutdown...
2023-12-05  9:38:17 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2023-12-05  9:38:17 0 [Note] InnoDB: Buffer pool(s) dump completed at 231205  9:38:17
2023-12-05  9:38:17 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2023-12-05  9:38:17 0 [Note] InnoDB: Shutdown completed; log sequence number 47629; transaction id 15
2023-12-05  9:38:17 0 [Note] mariadbd: Shutdown complete
```

**Comment by Clem-Fern** [comment]
Thank's, nothing to do with my problem then.

Mariadb seems to run just fine anyway. Have you done any change about networking in your docker daemon ?
There is not logical reason that explain why rtabby_web_api can't connect to db as there are directly connected through internal network.

**Comment by mihha** [comment]
I didn't do any changes in the networking

As I said, the only thing that was changed was "volume" part and I did that before I started docker compose for the first time

**Comment by Clem-Fern** [comment]
Hey @mihha 

I just published a new version which run with one container only using sqlite.

As I don't really see what could cause your containers to not being able to talk with each other in your setup... You could try to use sqlite version as a workaround.

https://github.com/Clem-Fern/rtabby-web-api#getting-started-sqlite

**Comment by Clem-Fern** [comment]
It was pointed to me in another issue that this was not very clear from the docs.

You are not supposed to access the api through a browser. You have to add your service url and your token added in `users.yml` directly in Tabby Config Sync tab.

**Comment by mihha** [comment]
Well, that is the problem

There is no place to add token anywhere in Tabby Config Sync tab
![image](https://github.com/Clem-Fern/rtabby-web-api/assets/3791124/caecacc2-93df-4649-9545-4931d9e720b0)

I am using the latest version of Tabby, which is 1.0.204

**Comment by Clem-Fern** [comment]
Oh i see what your problem is then.

The token field was missing due to a bug in this version. It has been fixed in 1.0.205

**Comment by mihha** [comment]
``I apologize for not realizing that there is a new version. It never showed up in the Tabby interface and I did check

Getting closer, but still not there

When I enter my sync host and the token, I get only spinning icon in the token field
![image](https://github.com/Clem-Fern/rtabby-web-api/assets/3791124/47ee985a-4485-4d62-91f0-ccaf37b322f8)

Docker logs shows the following
```
[2023-12-08T13:57:27Z INFO  rtabby_web_api] Running v0.3.0
[2023-12-08T13:57:27Z INFO  rtabby_web_api] users.yml loaded => 1 users found
[2023-12-08T13:57:27Z INFO  rtabby_web_api] Binding HTTP Listener on 0.0.0.0:8080
[2023-12-08T13:57:27Z INFO  rtabby_web_api] Starting HTTP Listener on 0.0.0.0:8080
[2023-12-08T13:57:27Z INFO  actix_server::builder] starting 4 workers
[2023-12-08T13:57:27Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-12-08T13:59:04Z INFO  rtabby-web-api] 172.25.0.1 "GET /api/1/configs/14101 HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tabby/1.0.205 Chrome/118.0.5993.144 Electron/27.1.0 Safari/537.36" 0.001130
```

Something is still missing.

Apache reverse proxy logs shows that the connection request reached the server, but then it just throws Error 401

**Comment by mihha** [comment]
Thank you for your efforts

I tried to do that and it didn't work

I even tried to clear the config completely and start fresh. No go as well

Although I thought that my reverse proxy is working correctly, now I start to wonder if that is the case

Do you have this behind the proxy? What proxy are you using? What is the config for the proxy if you are using it?

**Comment by mihha** [comment]
GUESS WHAT?

It was reverse proxy. I forgot to redirect all the HTTP requests to the HTTPS in the virtual host configuration

It seems like the config was uploaded now, but in tabby interface I get something funny
![image](https://github.com/Clem-Fern/rtabby-web-api/assets/3791124/eb6eede4-abb4-4bb5-add0-a40e3c7a1e8f)

It says that the sync configuration is wrong, but after that, that the config was uploaded correctly

**Comment by mihha** [comment]
Yes, I have a sync plugin installed, but it is not configured

I have disabled it with the same sync error message
![image](https://github.com/Clem-Fern/rtabby-web-api/assets/3791124/742e62c4-0903-4bfb-b6ed-cda0febe8bb4)

When I completely uninstalled it, the sync was working without any error messages

Thank you again for your effort in resolving the problem

I have learned a lot during the debugging of this. Specifically, not to trust something I believed was working correctly from my side (reverse proxy configuration

I apologize for spending so much of your time on something that wasn't your fault

**Comment by Clem-Fern** [comment]
I will try to add vhost configuration template for apache and nginx. It could always be usefull to someone.
